version: "3.1"
services:
  webserver:
    image: nginx:alpine
    container_name: audioteka-nginx
    working_dir: /app
    volumes:
      - .:/app
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8686:80"

  php-fpm:
    build: .
    container_name: audioteka-php
    working_dir: /app
    volumes:
      - .:/app
    expose:
      - "9000"
    user: 1000:1000

  mariadb:
    image: mariadb:10.4
    container_name: audioteka-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: audioteka_db
      MYSQL_USER: audioteka_user
      MYSQL_PASSWORD: password
    volumes:
      - ./docker/mariadb/data:/var/lib/mysql
    ports:
      - "8688:3306"
