App\Entity\Cart:
  attributes:
    pagination_items_per_page: 3
    denormalization_context:
      groups: ["cart:write"]
    normalization_context:
      groups: ["cart:read", "product:read", "money:read", "user:read"]
    security: 'is_granted("ROLE_ADMIN") or object.getUser() == user'

  itemOperations:
    get: ~
    delete: ~
    patch:
      security: "object.user == user"

    addProduct:
      method: POST
      path: /carts/{id}/products/{productId}
      controller: App\Controller\Cart\CartAddProductAction
      denormalization_context:
        groups: ~
      input: false
      write: false
    deleteProduct:
      method: DELETE
      status: 200
      path: /carts/{id}/products/{productId}
      controller: App\Controller\Cart\CartDeleteProductAction
      denormalization_context:
        groups: ~
      input: false
      write: false

  collectionOperations:
    post:
      input: false
      write: false
      security: 'is_granted("IS_AUTHENTICATED_ANONYMOUSLY")'
      security_post_denormalize: 'is_granted("IS_AUTHENTICATED_ANONYMOUSLY")'
#      "object.getUser() == user"
      controller: App\Controller\Cart\CartCreateAction
    get: ~
