App\Entity\Cart:
  attributes:
    pagination_items_per_page: 3
    denormalization_context:
      groups: ["cart:write"]
    normalization_context:
      groups: ["cart:read", "product:read", "money:read", "user:read"]
    security: "is_granted('ROLE_ADMIN') or object.user == user"

  itemOperations:
    get: ~
    delete: ~
    patch:
      security: "object.user == user"

  collectionOperations:
    post:
      security: false
      security_post_denormalize: "object.user == user"
    get: ~
