App\Entity\Product:
  attributes:
    pagination_items_per_page: 3
    denormalization_context:
      groups: ["product:write", "money:write"]
    normalization_context:
      groups: ["product:read", "money:read"]

  itemOperations:
    get: ~
    delete:
      security: is_granted('ROLE_ADMIN')
    patch:
      security: is_granted('ROLE_ADMIN')

  collectionOperations:
    post:
      security: is_granted('ROLE_ADMIN')
    get: ~
